CREATE TABLE users(
	blid INTEGER NOT NULL,
	password VARCHAR(255) NOT NULL,
	PRIMARY KEY(blid)
);

CREATE TABLE wrappers(
	pubkey VARCHAR(500) NOT NULL,
	blid INTEGER NOT NULL,
	PRIMARY KEY(pubkey),
	FOREIGN KEY(blid) REFERENCES users(blid) ON DELETE CASCADE
);